### ISSUE TITLE
Random file names

### ISSUE THREAD

**Issue by Cubly** [WaveringAna/embedder#18]
An option for random file names when uploading would be nice!

**Comment by WaveringAna** [comment]
Thats something ive been wanting to expose on the front end when I have time to refactor the entire thing, I think temporarily I can make that an option through an ENV.

**Comment by WaveringAna** [comment]
its pushed and live now, you can set it through EB_RANDOMIZE_NAMES and setting it to true.

https://github.com/WaveringAna/embedder/commit/ae2cdada07dba6b306cd017f7874d72a0f732854
