### ISSUE TITLE
404 for files with uppercase extensions

### ISSUE THREAD

**Issue by casem** [WaveringAna/embedder#7]
For example, uploading an image with the extension ".jpg" works but the same file with ".JPG" does the following:
- Causes the index page to display a broken image
- 404 error page when linking to the image

I was able to reproduce the issue using jpg and mp4. I didn't try the other supported formats.

**Comment by WaveringAna** [comment]
im not sure whats causing it to just not upload entirely but the first issue is caused by the front end being case sensitive, should be an easy fix

**Comment by WaveringAna** [comment]
alright, latest docker image and github release 1.2.3 should have this fixed but I'm going to leave this open because I want to see why express doesn't want to serve files with uppercase extensions because it does upload
